#name: Hello World
#on: [push]
#env:
#  variable: var1
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    env:
#      nombre : 15
#    steps:
#      - uses: actions/checkout@v3
#      - name: Hello World
#        run: echo Hello World !  $variable $nombre
 
name: Push and Pull Request
on: [push, pull_request]

env:
  mpush: "C'est un push !"
#  mpull: C'est une pull request!

jobs:
  push_ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push
        run: echo $mpush
      
  pull_request_ci:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'pull_request' }}
    steps:
      - uses: actions/checkout@v3
      - name: Pull Request
        run: echo $mpull       
